### ISSUE TITLE
Markbot's Performance check never finishes

### ISSUE THREAD

**Issue by prim0062** [prim0062/fastness-fixer#1]
As title states, Markbot never finishes the performance check portion of this exercise. Everything else passes the tests. I've uninstalled and reinstalled Markbot with no luck.
@charlie-quinn
![markbot no performance](https://user-images.githubusercontent.com/43246445/70365099-b1aab000-185d-11ea-874f-88db9802d8ee.png)

**Comment by charlie-quinn** [comment]
This assignment has been updated. 🤖✅

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`
